#!/usr/bin/ruby

print "Content-Type: text/html\n\n"
print "<html><head>"
print "<meta charset='UTF-8'>"
print "<title></title></head>"
print "<body>"
print "<h1>Get Form:</h1>"
print "<form action ="processdata.cgi" method ="get">"
print "<input type="text" name="username" placeholder="Username">"
print "<input type ="password" name= "userpassword" placeholder="Password">"
print "<input type="number" name="magicnumber" placeholder="Magic Number">"
print "<input type="submit" value="Submit">"
print "</form>"
print "<h2>Post Form:</h2>"
print "<form action ="processdata.cgi" method = "post">"
print "<input type="text" name="username" placeholder="Username">"
print "<input type= "password" name="userpassword" placeholder="Password" >"
print "<input type="number" name="magicnumber" placeholder="Magic Number">"
print "<input type="submit" value="Submit">"
print "</form>"
print "</body>\n</html>"
