#!/usr/bin/ruby

print "Content-Type: text/html\n\n"
print "<html><head>"
print "<meta charset='UTF-8'>"
print "<title></title></head>"
print "<body>"
print "<h2>Get Form:</h2>"
print "<form action ='processdata.cgi' method ='get'>"
print "<input type='text' name='username' placeholder='Username' required='true'>"
print "<input type='password' name= 'userpassword' placeholder='Password' required='true'>"
print "<input type='number' name='magicnumber' placeholder='Magic Number' required='true'>"
print "<br/>"
print "<input type='submit' value='Submit'>"
print "</form>"
print "<h2>Post Form:</h2>"
print "<form action ='processdata.cgi' method = 'post'>"
print "<input type='text' name='username' placeholder='Username' required='true'>"
print "<input type='password' name='userpassword' placeholder='Password' required='true'>"
print "<input type='number' name='magicnumber' placeholder='Magic Number' required='true'>"
print "<br/>"
print "<input type='submit' value='Submit'>"
print "</form>"
print "</body></html>"
