#!/usr/bin/ruby
<<<<<<< HEAD
print "Content-Type: text/html charset=UTF8 \n\n"
puts "<!DOCTYPE html>"
print "<html><head>"
print "<meta charset=\"UTF-8\">"
puts '<title></title></head>'
puts "<body>"
puts "<h1>Get Form:</h1>"
puts "<form action ="processdata.cgi" method = "get">"
puts "<input type="text" name="username" placeholder="Username">"
puts "<input type ="password" name= "userpassword" placeholder="Password">"
puts "<input type="number" name="magicnumber" placeholder="Magic Number">"
puts "<input type="submit" value="Submit">"
puts "</form>"
puts "<h2>Get Form:</h2>"
puts "<form action ="processdata.cgi" method = "post">"
puts "<input type="text" name="username" placeholder="Username">"
puts "<input type= "password" name="userpassword" placeholder="Password" >"
puts "<input type="number" name="magicnumber" placeholder="Magic Number">"
puts " <input type="submit" value="Submit"> "
puts "</form>"
print"</body>\n</html>"
=======

print "Content-Type: text/html\n\n"
print "<html><head>"
print "<title>Get vs Post Ruby</title></head>"
print "<bordy>"
print "<form action ='processdata.cgi' method = 'get'>"
print "<h1>Get Form:</h1>"
print "<br/>"
print "<input type='text' name='username' placeholder='Username' required='true'>"
print "<input type ='password' name= 'userpassword' placeholder='Password' required='true'>"
print "<input type='number' name='magicnumber' placeholder='Magic Number' required='true'>"
print "<br/>"
print "<input type='submit' value='Submit'>"
print "</form>"

print "<form action ='processdata.cgi' method = 'post'>"
print "<h1>Post Form:</h1>"
print "<br/>"
print "<input type='text' name='username' placeholder='Username' required='true'>"
print "<input type ='password' name= 'userpassword' placeholder='Password' required='true'>"
print "<input type='number' name='magicnumber' placeholder='Magic Number' required='true'>"
print "<br/>"
print "<input type='submit' value='Submit'>"
print "</form>"
print "</body>"
print "</html>"
>>>>>>> 19e5e749e425e61cd366c4d494beffe5d97a9698

